[package]
name = "cairovm_verifier_wasm"
description.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
serde_json.workspace = true
wasm-bindgen.workspace = true

cairovm_verifier_air = { workspace = true, default-features = false }
cairovm_verifier_stark = { workspace = true, default-features = false }
cairovm_verifier_proof_parser = { workspace = true, default-features = false }

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.15", features = ["js"] }

[features]
default = ["recursive", "keccak"]
dex = []
recursive = []
recursive_with_poseidon = []
small = []
starknet = []
starknet_with_keccak = []
keccak = []
blake2s = []