[package]
name = "wasm-binding"
description.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
wasm-bindgen.workspace = true
getrandom = { version = "0.2.15", features = ["js"] }
serde_json = "1.0.114"

cairovm_verifier_air = { workspace = true, features = ["default"] }
cairovm_verifier_proof_parser = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.15", features = ["js"] }
