[profile.release]
overflow-checks = true

[workspace]
resolver = "2"
members = [
    "crates/air",
    "crates/transcript",
    "crates/commitment",
    "crates/fri",
    "crates/pow",
    "crates/stark",
    "proof-parser",
    "cli", "wasm-binding",
]
exclude = []

[workspace.package]
description = "Swiftness - Rust CairoVM Verifier implementation"
edition = "2021"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/iosis-tech/swiftness"
version = "0.0.3"

[workspace.dependencies]
bail-out = "0.2.0"
serde_json = "1.0.114"
serde = { version = "1.0", features = ["derive"] }
serde_with = "2.3.2"
sha3 = "0.10.8"
starknet-core = "0.11.1"
starknet-crypto = "0.7.1"
starknet-types-core = "0.1.5"
crypto-bigint = "0.5.5"
thiserror = "1.0.61"
num-bigint = { version = "0.4.4", features = ["serde"] }
blake2 = "0.10.6"
wasm-bindgen = "0.2"

swiftness_air = { version = "0.0.3", path = "crates/air", default-features = false }
swiftness_commitment = { version = "0.0.3", path = "crates/commitment", default-features = false }
swiftness_fri = { version = "0.0.3", path = "crates/fri", default-features = false }
swiftness_pow = { version = "0.0.3", path = "crates/pow", default-features = false }
swiftness_stark = { version = "0.0.3", path = "crates/stark", default-features = false }
swiftness_transcript = { version = "0.0.3", path = "crates/transcript", default-features = false }
swiftness_proof_parser = { version = "0.0.3", path = "proof-parser", default-features = false }
