[package]
name = "swiftness_wasm"
description = "Swiftness CairoVM Verifier | swiftness-{layout}-{commitment hash}"
edition.workspace = true
license-file.workspace = true
readme = "README.md"
repository.workspace = true
version.workspace = true

[dependencies]
wasm-bindgen = "0.2"
serde_json.workspace = true
swiftness_proof_parser = { path = "../proof_parser", default-features = false, version = "0.0.5" }

swiftness_air = { workspace = true }
swiftness_stark = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.15", features = ["js"] }

[features]
default = ["std", "recursive", "keccak"]
std = [
    "swiftness_air/std",
    "swiftness_stark/std",
]
dex = ["swiftness_air/dex", "swiftness_stark/dex"]
recursive = [
    "swiftness_air/recursive",
    "swiftness_stark/recursive",
]
recursive_with_poseidon = [
    "swiftness_air/recursive_with_poseidon",
    "swiftness_stark/recursive_with_poseidon",
]
small = ["swiftness_air/small", "swiftness_stark/small"]
starknet = ["swiftness_air/starknet", "swiftness_stark/starknet"]
starknet_with_keccak = [
    "swiftness_air/starknet_with_keccak",
    "swiftness_stark/starknet_with_keccak",
]
keccak = [
    "swiftness_stark/keccak",
]
blake2s = [
    "swiftness_stark/blake2s",
]