[package]
name = "swiftness_cli"
description.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.4.4", features = ["derive"] }
thiserror.workspace = true
starknet-crypto.workspace = true

swiftness_air = { workspace = true, default-features = false }
swiftness_stark = { workspace = true, default-features = false }
swiftness_proof_parser = { workspace = true, default-features = false }

[features]
default = ["recursive", "keccak"]
dex = []
recursive = []
recursive_with_poseidon = []
small = []
starknet = []
starknet_with_keccak = []
keccak = []
blake2s = []