[package]
name = "cairovm_verifier_cli"
description.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.4.4", features = ["derive"] }
thiserror.workspace = true
starknet-crypto.workspace = true
cairovm_verifier_proof_parser.workspace = true
cairovm_verifier_stark.workspace = true
cairovm_verifier_air.workspace = true


[features]
default = ["recursive"]
dex = []
recursive = []
recursive_with_poseidon = []
small = []
starknet = []
starknet_with_keccak = []