[package]
name = "swiftness"
description.workspace = true
edition.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.4.4", features = ["derive"] }
starknet-crypto.workspace = true

swiftness_air = { workspace = true }
swiftness_stark = { workspace = true }
swiftness_proof_parser = { workspace = true }

[features]
default = ["starknet_with_keccak", "blake2s"]
dex = []
recursive = []
recursive_with_poseidon = []
small = []
starknet = []
starknet_with_keccak = []
keccak = []
blake2s = []
