[package]
name = "cairovm_verifier_cli"
description.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.4.4", features = ["derive"] }
starknet-crypto.workspace = true

cairovm_verifier_air = { path = "../crates/air", features = ["std"] }
cairovm_verifier_stark = { path = "../crates/stark", features = ["std"] }
cairovm_verifier_proof_parser = { path = "../proof-parser", features = ["std"] }

[features]
default = ["recursive", "keccak"]
dex = []
recursive = []
recursive_with_poseidon = []
small = []
starknet = []
starknet_with_keccak = []
keccak = []
blake2s = []
