[package]
name = "ensure_no_std"
version = "0.1.0"
edition = "2021"

[dependencies]
cairovm_verifier_air = { workspace = true, default-features = false }
cairovm_verifier_stark = { workspace = true, default-features = false }
cairovm_verifier_proof_parser = { workspace = true, default-features = false }

[features]
default = ["recursive", "keccak"]
dex = []
recursive = []
recursive_with_poseidon = []
small = []
starknet = []
starknet_with_keccak = []
keccak = []
blake2s = []
