[package]
name = "cairovm_verifier_fri"
description.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = ["std"]
std = ["dep:thiserror"]
keccak = []
blake2s = []

[dependencies]
serde_with.workspace = true
serde.workspace = true
sha3.workspace = true
starknet-core.workspace = true
starknet-crypto.workspace = true
thiserror = { optional = true, workspace = true }
thiserror-no-std.workspace = true

cairovm_verifier_air.workspace = true
cairovm_verifier_commitment.workspace = true
cairovm_verifier_transcript.workspace = true
