[package]
name = "swiftness_proof_parser"
description.workspace = true
edition.workspace = true
license-file.workspace = true
readme = "README.md"
repository.workspace = true
version.workspace = true

[features]
default = ["std", "keccak", "recursive"]
std = [
    "serde/std",
    "starknet-types-core/std",
    "num-bigint/std",
    "anyhow/std",
    "clap/std",
    "regex/std",
    "serde_json/std",
]
dex = []
recursive = []
recursive_with_poseidon = []
small = []
starknet = []
starknet_with_keccak = []
keccak = []
blake2s = []


[dependencies]
serde.workspace = true
thiserror.workspace = true
starknet-types-core.workspace = true
num-bigint.workspace = true
anyhow = "1.0.80"
clap = { version = "4.5.1", features = ["derive"] }
regex = "1.10.3"
serde_json = "1.0.114"

swiftness_stark.workspace = true
swiftness_commitment.workspace = true
swiftness_fri.workspace = true
swiftness_air.workspace = true
swiftness_pow.workspace = true
