[package]
name = "swiftness_proof_parser"
description = "Swiftness - Rust CairoVM Verifier implementation"
edition = "2021"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/iosis-tech/swiftness"
version = "0.0.5"

[features]
default = ["std", "keccak", "recursive"]
std = [
    "swiftness_air/std",
    "swiftness_commitment/std",
    "swiftness_fri/std",
    "swiftness_pow/std",
    "swiftness_stark/std",
    "swiftness_transcript/std",
]
dex = []
recursive = []
recursive_with_poseidon = []
small = []
starknet = []
starknet_with_keccak = []
keccak = []
blake2s = []


[dependencies]
serde = "1.0"
thiserror = "1.0.61"
starknet-types-core = "0.1.5"
num-bigint = { version = "0.4.4", features = ["serde"] }
anyhow = "1.0.80"
clap = { version = "4.5.1", features = ["derive"] }
regex = "1.10.3"
serde_json = "1.0.114"

swiftness_air = { path = "../crates/air", default-features = false, version = "0.0.5" }
swiftness_commitment = { path = "../crates/commitment", default-features = false, version = "0.0.5" }
swiftness_fri = { path = "../crates/fri", default-features = false, version = "0.0.5" }
swiftness_pow = { path = "../crates/pow", default-features = false, version = "0.0.5" }
swiftness_stark = { path = "../crates/stark", default-features = false, version = "0.0.5" }
swiftness_transcript = { path = "../crates/transcript", default-features = false, version = "0.0.5" }
