[package]
name = "cairovm_verifier_commitment"
description.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
serde_with.workspace = true
starknet-crypto.workspace = true
starknet-core.workspace = true