name: Manual Publish to npm

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      WORKING_DIR: ${{ github.workspace }}/wasm_bindings

    strategy:
      fail-fast: false
      matrix:
        layout:
          [
            "dex",
            "dynamic",
            "recursive",
            "recursive_with_poseidon",
            "small",
            "starknet",
            "starknet_with_keccak",
          ]
        hash: 
          [
            "keccak_160_lsb",
            "keccak_248_lsb",
            "blake2s_160_lsb",
            "blake2s_248_lsb",
          ]
        stone: 
          [
            "stone5",
            "stone6",
          ]


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Configure npm
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
        working-directory: ${{ env.WORKING_DIR }}

      - name: Cache Cargo registry
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo build
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build package
        run: wasm-pack build --out-dir pkg --target web --features ${{ matrix.layout }},${{ matrix.hash }},${{ matrix.stone }} --no-default-features
        working-directory: ${{ env.WORKING_DIR }}

      - name: Rename package
        run: |
          jq --arg layout "${{ matrix.layout }}" --arg hash "${{ matrix.hash }}" --arg stone "${{ matrix.stone }}" \
            '.name = "swiftness-\($layout | gsub("_"; "-"))-\($hash | gsub("_"; "-"))-\($stone | gsub("_"; "-"))"' \
            package.json > tmp.json && mv tmp.json package.json
        working-directory: ${{ env.WORKING_DIR }}/pkg

      - name: Publish to npm
        run: npm publish
        working-directory: ${{ env.WORKING_DIR }}/pkg
